name: Docker Dev Image
permissions:
  contents: read
  packages: write
on:
  push:
    branches: [ dev ]
    paths-ignore:
      - 'README.md'
      - 'README-cn.md'
      - 'README-docker.md'
      - 'LICENSE'
      - '**.md'
      - 'src/version.h'
      - '.github/workflows/build.yml'
      - '.github/workflows/clean_failed_cancelled_runs.yml'
      - '.github/workflows/openwrt.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  REGISTRY_IMAGE: aethersailor/subconverter

jobs:
  build-dockerhub:
    runs-on: ubuntu-latest
    name: Build amd64 for Docker Hub
    steps:
      - name: Checkout base
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: scripts/
          build-args: |
            SHA=${{ steps.vars.outputs.sha_short }}
            BRANCH=${{ github.ref_name }}
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:dev
          no-cache: true

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:dev